/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerBairro;
import controller.ControllerCidade;
import controller.ControllerCliente;//controle de cadastro de cliente
import controller.ControllerCidadeEstado;
import controller.ControllerClienteCidadeBairroUf;
import controller.ControllerEstado;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.*;
import util.ModeloTabela;

/**
 *
 * @author wellington
 */
public class ViewCadCliente extends javax.swing.JFrame {

    private String funcao = "salvar";
    private String funcao2;
    
    private ModelCliente mCadCliente;//Declarando o modelo do banco cliente
    private ControllerCliente cCadCliente;
    
    private ModelClienteCidadeBairroUf mCliCiBaUf;
    private ControllerClienteCidadeBairroUf cCliCiBaUf;
    
    private ControllerEstado cEstado;
    private ControllerCidade cCidade;
    private ControllerBairro cBairro;
    
    /**
     * Creates new form ViewCadCliente
     */
    public ViewCadCliente() {
        initComponents();
        setLocationRelativeTo(null);//tela no centro
        txtcodigo.setEditable(false);//permanecer desabilitado
        desabilitarcomponentes();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
       
        
        mCadCliente = new ModelCliente();
        cCadCliente = new ControllerCliente();
        
        mCliCiBaUf = new ModelClienteCidadeBairroUf();
        cCliCiBaUf = new ControllerClienteCidadeBairroUf();
        
        cCidade = new ControllerCidade();
        cBairro = new ControllerBairro();
        cEstado = new ControllerEstado();
        
        preenchertabela();
        listarEstados();
        listarCidades();
        listarBairro();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbcodigo = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        lbnome = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtcpf = new javax.swing.JTextField();
        lbcpf = new javax.swing.JLabel();
        lbemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txttelefone = new javax.swing.JTextField();
        txtcelular = new javax.swing.JTextField();
        lbtelefone = new javax.swing.JLabel();
        lbcelular = new javax.swing.JLabel();
        lbendereco = new javax.swing.JLabel();
        txtendereco = new javax.swing.JTextField();
        txtnumcasa = new javax.swing.JTextField();
        txtcomplemento = new javax.swing.JTextField();
        lbnumcasa = new javax.swing.JLabel();
        lbcomplemento = new javax.swing.JLabel();
        lbcidade = new javax.swing.JLabel();
        cbcidade = new javax.swing.JComboBox<>();
        lbbairro = new javax.swing.JLabel();
        cbbairro = new javax.swing.JComboBox<>();
        lbuf = new javax.swing.JLabel();
        cbuf = new javax.swing.JComboBox<>();
        txtcep = new javax.swing.JTextField();
        lbcep = new javax.swing.JLabel();
        lbpesquisa = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btCancelar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cliente");

        lbcodigo.setText("Código:");

        lbnome.setText("Nome Completo:");

        lbcpf.setText("CPF:");

        lbemail.setText("E-mail:");

        lbtelefone.setText("Telefone:");

        lbcelular.setText("Celular:");

        lbendereco.setText("Endereço:");

        lbnumcasa.setText("Nª:");

        lbcomplemento.setText("Complemento:");

        lbcidade.setText("Cidade:");

        lbbairro.setText("Bairro:");

        lbuf.setText("UF:");

        lbcep.setText("CEP:");

        lbpesquisa.setText("Pesquisa:");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbcodigo)
                                .addGap(93, 93, 93)
                                .addComponent(lbnome)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbcpf)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtcpf)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbemail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbtelefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbcelular)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtcelular, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbendereco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnumcasa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbnumcasa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbcomplemento)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtcomplemento)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbcidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbbairro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbuf)
                            .addComponent(cbuf, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbcep)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtcep)))
                    .addComponent(jTextField11)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbpesquisa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSalvar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbcodigo)
                    .addComponent(lbnome)
                    .addComponent(lbcpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbemail)
                    .addComponent(lbtelefone)
                    .addComponent(lbcelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbendereco)
                    .addComponent(lbnumcasa)
                    .addComponent(lbcomplemento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumcasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbcidade)
                    .addComponent(lbbairro)
                    .addComponent(lbuf)
                    .addComponent(lbcep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbpesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btExcluir)
                    .addComponent(btEditar)
                    .addComponent(btNovo)
                    .addComponent(btSalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        desabilitarcomponentes();//desabilita botoes e campos de texto
        limpartela();//limpa a tela
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        //retorna o indice da linha
        int linha = table.getSelectedRow();
            if(linha >= 0){
                //pergunta
                String descricao = "Deseja excluir o Cliente:"+table.getValueAt(linha,1)+"?";
                //obtem o valor verdadeiro ou falso (1,0)
                int opcao = JOptionPane.showConfirmDialog(null,descricao,"Atenção",JOptionPane.YES_NO_OPTION);
                    //faz a comparação
                    if(opcao == JOptionPane.YES_OPTION){
                        //pega o codigo do cliente
                        mCadCliente.setCli_id((int) (table.getValueAt(linha, 0)));
                        //passa para o delete
                        cCadCliente.delete(mCadCliente);
                        //assim que o usuario e excluido
                        //atualiza a tebela
                        preenchertabela();
                    }
                    else{
                        //senao quiser excluir cliente
                        //desabilita os camppos
                       desabilitarcomponentes();
                    }
            }
            else{
                JOptionPane.showMessageDialog(null, "Selecione um campo no banco de dados!");
            }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
            funcao = "editar";//add a função editar para a variavel
            habilitacomponentes();//habilita campos e botoes
            pegadadosdatabela();//e recupera os dados da tabela
            
    }//GEN-LAST:event_btEditarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        //abilita campos e botoes
                habilitacomponentes();
                //limpa a tela
                limpartela();
                //add a fução novo
                funcao = "salvar";
    }//GEN-LAST:event_btNovoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        //para salvar depende da funcao se recebeu salvar ou editar
            //se funcao receber salvar ao clickar no botao novo ele excuta
            //o insert
            if(funcao.equals("salvar")){
               //insert recebe os dados dos campos de texto
               //retorna para a insersão ao banco
               cCadCliente.insert(montarCliente("salvar"));
               //apos desabilita os campos
               habilitacomponentes();
               //limpa a tela
               limpartela();
               //atualiza a tabela
               preenchertabela();
               desabilitarcomponentes();
               limpartela();
               
            }
            else{//senao for salvar, foi clickado no boatao editar
               //e o metodo montar tela pega os dados do campo
               //e retorna para update atualizar as informações do
               //usuario
               cCadCliente.update(montarCliente("editar"));
               //desabilita os campos
               desabilitarcomponentes();
               //limpa a tela
               limpartela();
               //atualiza a tabela
               preenchertabela();
            }
    }//GEN-LAST:event_btSalvarActionPerformed

    /*================================================OUTROS METODOS========================================*/
    //metodo para desabilitar componentes
    private void desabilitarcomponentes(){//inicio
        txtnome.setEditable(false);
        txtcpf.setEditable(false);
        txtemail.setEditable(false);
        txttelefone.setEditable(false);
        txtcelular.setEditable(false);
        txtendereco.setEditable(false);
        txtnumcasa.setEditable(false);;
        txtcomplemento.setEditable(false);
        txtcep.setEditable(false);
        
        cbbairro.setEnabled(false);
        cbcidade.setEnabled(false);
        cbuf.setEnabled(false);
        
        btCancelar.setEnabled(false);
        btSalvar.setEnabled(false);
        
        btNovo.setEnabled(true);
        btEditar.setEnabled(true);
        btExcluir.setEnabled(true);
        

    }//fim metodo desabilitarcomponentes
    
    //metodo habilitar componentes
    private void habilitacomponentes(){
        
        txtnome.setEditable(true);
        txtcpf.setEditable(true);
        txtemail.setEditable(true);
        txttelefone.setEditable(true);
        txtcelular.setEditable(true);
        txtendereco.setEditable(true);
        txtnumcasa.setEditable(true);
        txtcomplemento.setEditable(true);
        txtcep.setEditable(true);
        
        cbbairro.setEnabled(true);
        cbcidade.setEnabled(true);
        cbuf.setEnabled(true);
        
        btCancelar.setEnabled(true);
        btSalvar.setEnabled(true);
        
        btNovo.setEnabled(false);
        btEditar.setEnabled(false);
        btExcluir.setEnabled(false);
        
    }//fim metodo de habilitar componentes
    
    //metodo para limpar campos
    private void limpartela(){//incio
        txtcodigo.setText("");
        txtnome.setText("");
        txtcpf.setText("");
        txtemail.setText("");
        txttelefone.setText("");
        txtcelular.setText("");
        txtendereco.setText("");
        txtnumcasa.setText("");
        txtcomplemento.setText("");
        txtcep.setText("");
    }//fim do metodo limpa campos
    
        //metodo para obter dados do campos de texto
    //retorna o objeto do modelo cliente
    //o controle recebe o modelo, para cadastrar autlizar ou excluir
    private ModelCliente montarCliente(String funcao){
	//modelo
	mCadCliente = new ModelCliente();
	//codicao
            if(funcao.equals("salvar")){
		mCadCliente.setCli_nome(txtnome.getText());
		mCadCliente.setCli_cpf(txtcpf.getText());
		mCadCliente.setCli_email(txtemail.getText());
		mCadCliente.setCli_telefone(txttelefone.getText());
		mCadCliente.setCli_celular(txtcelular.getText());
		mCadCliente.setCli_endereco(txtendereco.getText());
		mCadCliente.setCli_numcasa(txtnumcasa.getText());
		mCadCliente.setCli_complemento(txtcomplemento.getText());
		mCadCliente.setCli_bairro(cbbairro.getSelectedIndex()+1);
		mCadCliente.setCli_idcidade(cbcidade.getSelectedIndex()+1);
		mCadCliente.setCli_idestado(cbuf.getSelectedIndex()+1);
		mCadCliente.setCli_cep(txtcep.getText());
		}
            else{	
		mCadCliente.setCli_nome(txtnome.getText());
		mCadCliente.setCli_cpf(txtcpf.getText());
		mCadCliente.setCli_email(txtemail.getText());
		mCadCliente.setCli_telefone(txttelefone.getText());
		mCadCliente.setCli_celular(txtcelular.getText());
		mCadCliente.setCli_endereco(txtendereco.getText());
		mCadCliente.setCli_numcasa(txtnumcasa.getText());
		mCadCliente.setCli_complemento(txtcomplemento.getText());
		mCadCliente.setCli_bairro(cbbairro.getSelectedIndex()+1);
		mCadCliente.setCli_idcidade(cbcidade.getSelectedIndex()+1);
		mCadCliente.setCli_idestado(cbuf.getSelectedIndex()+1);
		mCadCliente.setCli_cep(txtcep.getText());
                    if (this.txtcodigo.getText() != null && !this.txtcodigo.getText().equals("")) {
			mCadCliente.setCli_id(Integer.parseInt(this.txtcodigo.getText()));
                    }
			
		}
		//retorno do objeto modelo
		return mCadCliente;
    }//fim metodo para construir tela
    
     //pegar dados da tabela e retorna para os campos
    private void pegadadosdatabela(){
     int linha = table.getSelectedRow();
     if(linha >= 0){
         //table retona a index da coluna (linha,coluna)
        txtcodigo.setText(""+table.getValueAt(linha, 0));
        txtnome.setText(""+table.getValueAt(linha, 1));
        txtcpf.setText(""+table.getValueAt(linha, 2));
        txtemail.setText(""+table.getValueAt(linha, 3));
        txttelefone.setText(""+table.getValueAt(linha, 4));
        txtcelular.setText(""+table.getValueAt(linha, 5));
        txtendereco.setText(""+table.getValueAt(linha, 6));
        txtnumcasa.setText(""+table.getValueAt(linha, 7));
        txtcomplemento.setText(""+table.getValueAt(linha, 8));
        txtcep.setText(""+table.getValueAt(linha, 12)); 
         
     }
     else{
        JOptionPane.showMessageDialog(null, "Selecione um campo na tabela!");
         desabilitarcomponentes();
     }
    }
    
    //metodo para modelo a tabela do form
    //e preencher o mesmo
    private void preenchertabela(){
		
	//ConexaoJdbc.executarSQL("Select * from cad_categoria");
	mCliCiBaUf = new ModelClienteCidadeBairroUf();
	cCliCiBaUf = new ControllerClienteCidadeBairroUf();
		
	//Lista de clientes recebe do controle o retorno de uma consulta no banco
	List<ModelClienteCidadeBairroUf> m = cCliCiBaUf.select();
	//criar o vetor dados para preencher a tabela
	ArrayList dados = new ArrayList();
		
	//para preencher as linhas da tabela com os dados
            for (ModelClienteCidadeBairroUf model : m) {
             //add cada dado em linhas da table
                dados.add(new Object[]{model.getId(),model.getNome(),model.getCpf(),
                model.getEmail(),model.getTelefone(),model.getCelular(),
		model.getEndereco(),model.getNumcasa(),model.getComplemento(),
		model.getBairro(), model.getCidade(), model.getUf(),
		model.getCep()
                });//fim dados.add
            }//fim for
		
            //seta um modelo da tabela com os dados em linhae colunas
            table.setModel(new ModeloTabela(dados,new String[] {"Código", "Nome", "CPF", "E-mail", "Telefone", "Celular", "Endereço",
				"Núm.Casa", "Complemento", "Bairro", "Cidade","UF", "CEP"}));
            table.getTableHeader().setReorderingAllowed(false);
            //para preencher cada campo com lagura de 50 e impedir que
            //seja remensionado false
                for(int i=0;i<12;i++){
		//table.getColumnModel().getColumn(i).setResizable(false);
                table.getColumnModel().getColumn(i).setPreferredWidth(100);
                 }
		table.setAutoResizeMode(table.AUTO_RESIZE_OFF);
		table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
	}//fim metodo preenchertabela
    
     //preencher combobox estado
    private void listarEstados(){
        this.cEstado = new ControllerEstado();
        List<ModelEstado> listEstado  = cEstado.select();
        cbuf.removeAllItems();
        for(ModelEstado mEstado : listEstado){
            cbuf.addItem(mEstado.getEstado_uf());
        }
    }
    private void listarCidades(){
        this.cCidade = new ControllerCidade();
        List<ModelCidade> listCidade = this.cCidade.select();
        cbcidade.removeAllItems();
        for(ModelCidade m : listCidade){
            cbcidade.addItem(m.getCid_nome());
        }
    }
     private void listarBairro(){
        this.cBairro = new ControllerBairro();
        List<ModelBairro> listBairro = this.cBairro.select();
        cbbairro.removeAllItems();
        for(ModelBairro m : listBairro){
            cbbairro.addItem(m.getBairro_nome());
        }
     }
    
    /*============================================================FIM DE OUTROS METODOS==================================*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> cbbairro;
    private javax.swing.JComboBox<String> cbcidade;
    private javax.swing.JComboBox<String> cbuf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JLabel lbbairro;
    private javax.swing.JLabel lbcelular;
    private javax.swing.JLabel lbcep;
    private javax.swing.JLabel lbcidade;
    private javax.swing.JLabel lbcodigo;
    private javax.swing.JLabel lbcomplemento;
    private javax.swing.JLabel lbcpf;
    private javax.swing.JLabel lbemail;
    private javax.swing.JLabel lbendereco;
    private javax.swing.JLabel lbnome;
    private javax.swing.JLabel lbnumcasa;
    private javax.swing.JLabel lbpesquisa;
    private javax.swing.JLabel lbtelefone;
    private javax.swing.JLabel lbuf;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtcelular;
    private javax.swing.JTextField txtcep;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcomplemento;
    private javax.swing.JTextField txtcpf;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnumcasa;
    private javax.swing.JTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}
